### ISSUE TITLE
hit300, hit300k and hit300g is annoying

### ISSUE THREAD

**Issue by yousef157** [eclipsedteam/Dashed#1]
hit300, hit300k and hit300g can be annoying while clicking stacks or streams.

Making them just blank will make us more focused while playing.

**Comment by Tanza3D** [comment]
[Fixed in latest commit](https://github.com/Hubza/Eclipsed/commit/73a9c3b0f450c4061773d57b104c543f3c7febc0)

This was planned, i did this a little while before you commented, i just havent been working much on this and never updated, im about to release an updated osk.
