### ISSUE TITLE
miss noise way too loud

### ISSUE THREAD

**Issue by 94mudkips** [eclipsedteam/Dashed#3]
once you miss there is basically no way of refocusing in time to not fail

**Comment by Tanza3D** [comment]
Replaced miss noise, i never noticed this myself since i play with 25% effect sound. - [Commit be9dd4f](https://github.com/Hubza/Eclipsed/commit/be9dd4f0750318c3c318407be5840b301a1d370f)

**Comment by yousef157** [comment]
Real nibbas play with 100% effect sound.

Because I do and that was fucking painful with this skin.

**Comment by Tanza3D** [comment]
@yousef157 all fixed now
