### ISSUE TITLE
'relax2' is meant to be autopilot

### ISSUE THREAD

**Issue by yousef157** [eclipsedteam/Dashed#4]
'selection-mod-relax2' is meant to be Autopilot but it says 'Relax' in-game.

Apparently there is 2 relaxes in the mod selection for the normal gamemode now.
Please fix.

**Comment by Tanza3D** [comment]
I got that alot, i just named it relax and always have because it says "relax" in the png name, i'll get on that in a few mins

**Comment by Tanza3D** [comment]
Fixed, its only updated in the "source code" of the project, im not going to release it until i fix some more things.

**Comment by yousef157** [comment]
> I got that alot, i just named it relax and always have because it says "relax" in the png name, i'll get on that in a few mins

Ah, that's a common mistake. It's ok though! Thanks for fixing it.

**Comment by Tanza3D** [comment]
> 
> 
> > I got that alot, i just named it relax and always have because it says "relax" in the png name, i'll get on that in a few mins
> 
> Ah, that's a common mistake. It's ok though! Thanks for fixing it.

i just felti t was better
