### ISSUE TITLE
Replace old grades with new grades

### ISSUE THREAD

**Issue by yousef157** [eclipsedteam/Dashed#6]
There are new grade textures now. A, B, C, D, S, SS and SSPlus. F is removed.
Didn't make a pull request on this one since I don't know how to enlarge the textures. So good luck on you.

A:

![A](https://user-images.githubusercontent.com/48018938/59160570-6b5fd880-8ae8-11e9-9bd1-5baf5135f787.png)

B:

![B](https://user-images.githubusercontent.com/48018938/59160575-7155b980-8ae8-11e9-8629-b4e574323d2c.png)

C:

![C](https://user-images.githubusercontent.com/48018938/59160580-7c104e80-8ae8-11e9-9520-1afb874cfff2.png)

D:

![D](https://user-images.githubusercontent.com/48018938/59160583-816d9900-8ae8-11e9-8ab5-03277367ba8d.png)

S:

![S](https://user-images.githubusercontent.com/48018938/59160589-8894a700-8ae8-11e9-8999-49c26a833995.png)

SS:

![SS](https://user-images.githubusercontent.com/48018938/59160594-921e0f00-8ae8-11e9-8379-105f22502eac.png)

SSPlus:

![SSPlus](https://user-images.githubusercontent.com/48018938/59160597-9813f000-8ae8-11e9-9e94-8d0810cc3226.png)

**Comment by Tanza3D** [comment]
I've been thinking about doing this but as a designer i hate these new ones, - im going to replace them with something i made sometime soon - https://twitter.com/hubziii/status/1133732868314861569/photo/1
